image: node:16.6.2

pipelines:
  branches:
    master:
      - step:
          name: Installing and Building the App
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - build/**
            
      - step:
          name: Deploy to AWS S3
          deployment: staging
          script:
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $STAGING_BUCKET_NAME
                LOCAL_PATH: 'build'